# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('agency', models.CharField(blank=True, max_length=64, null=True)),
                ('role', models.CharField(blank=True, choices=[(b'Medical Responder', b'Medical Responder'), (b'Firefighter', b'Firefighter'), (b'Administrator', b'Administrator'), (b'Radio Hobbiest', b'Radio Hobbiest'), (b'Law Enforcement', b'Law Enforcement'), (b'Public Works', b'Public Works'), (b'Other Government Employee', b'Other Government Employee'), (b'Technical', b'Technical')], max_length=256, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
