# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '__first__'),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=512)),
                ('category', models.CharField(choices=[(b'Private Residence', b'Private Residence'), (b'Shared Residence', b'Shared Residence'), (b'Business', b'Business'), (b'Commercial Structure', b'Commercial Structure'), (b'Vacation Home', b'Vacation Home'), (b'Apartments/Complex', b'Apartments/Complex')], max_length=256)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people.Account')),
                ('poi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='map.FixedLocation')),
            ],
        ),
        migrations.AlterField(
            model_name='incident',
            name='dispatch_time',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='payload',
            field=models.CharField(editable=False, max_length=10000),
        ),
    ]
