# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='unique_id',
            field=models.CharField(default=b'3c5bb56', max_length=8),
        ),
    ]
