# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20160307_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='unique_id',
            field=models.CharField(default=b'2bf7cc7', max_length=8),
        ),
    ]
