# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0004_auto_20160315_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fountain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False)),
                ('stream', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='agency',
            name='unique_id',
            field=models.CharField(default=b'f152567', max_length=8),
        ),
        migrations.CreateModel(
            name='TwitterFountain',
            fields=[
                ('fountain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='map.Fountain')),
                ('twitter_username', models.CharField(max_length=256, null=True)),
                ('twitter_id', models.CharField(max_length=256, null=True)),
                ('url', models.URLField(null=True)),
            ],
            bases=('map.fountain',),
        ),
        migrations.AddField(
            model_name='fountain',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fountains', to=settings.AUTH_USER_MODEL),
        ),
    ]
