# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20160315_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fountain',
            name='stream',
        ),
        migrations.AddField(
            model_name='twitterfountain',
            name='stream',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='unique_id',
            field=models.CharField(default=b'2918bb0', max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='twitterfountain',
            unique_together=set([('twitter_username', 'twitter_id')]),
        ),
    ]
